### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by maxrimue** [bcoe/yargs#310]
This issue is thought to be a central place for discussing ideas for version 4.0.0 of yargs. Feel free to edit this message as ideas change or are added, I'll try to keep it up-to-date.

## New features
- [ ] <strike>Reading args in the order they were passed rather than in the order they were defined in the yargs configuration (#39) </strike>
- [ ] Add type `number` with default value (#110)
- [ ] <strike>Allowing a mixture of `boolean`, `alias` and `default` (#112) </strike>
- [ ] <strike>Aliases for commands (#121)</strike>
- [x] Allowing to require commands (#174/#287) 
- [ ] <strike>Support passing paths with defaults to commands (#201)</strike>
- [ ] <strike>Fully support nested objects as options (#292)</strike>
- [ ] <strike>Making argv object simpler in order to be able to a create a wrapper for the API (#294)</strike>
- [x] Support invoking configuration from `package.json` file (#303)
- [x] Add default value for `version` parameter in `.version()` (#337) (merged: #343) 
- [x] Enable further customization (#352) 

## Fixing
- [ ] <strike>Make the documentation more readable (drop pirate language except for introduction, standardised way of documenting all features: #92) (move installation instructions to the top: #323).</strike> we've put a lot of work into a website, which we can continue to iterate on; the goal is to introduce people to yargs in an elegant way.
- [ ] <strike>Specifying both `count` and `boolean` should make yargs throw an error/warning (#307)</strike>
- [x] Fix nested subcommand order (#313)
- [x] Fix inconsistency with ~~`.version()`~~ (merged: #330) and `.default()` API (#329)

You can discuss each feature in this issue. If wished, I can also add additional information to issues tomorrow as I'm right now a little short on time. Adding/removing items can either be proposed or just done by collaborators.

## Breaking changes in `4.x`
- PR #330: `.version()` method now expects the version argument to be last instead of first. The `version` parameter has highest priority, `option` has second and `description` third:
```javascript
 .version(option, description, version) //Or
 .version(option, version) //Or
 .version(version)
```

**Comment by bcoe** [comment]
@maxrimue thanks for taking the time to put this together :+1: I'll make an effort to provide thorough feedback this weekend.

**Comment by maxrimue** [comment]
Cool! I'll get into detail with each issue this weekend so I can
participate in discussing, if there's anything else I can do, let me know.
Benjamin E. Coe <notifications@github.com> schrieb am Fr., 4. Dez. 2015 um
06:56:

**Comment by maxrimue** [comment]
Okay, I thought I could start with my own opinion so you have something to comment on.

First of all, I think the amount of changes as currently drafted here seems okay for a new major release, as it does cause major changes in semantic versioning, but I believe that these changes <i>won't</i> break <i>much</i> real code, I think only #39 could cause new unexpected behaviour for people that rely on `switch`es for argument processing, although I don't think much people do that.

We should also decide whether or whether not v3 will still be maintained (<i>for example in another branch?</i>) for critical fixes. You could argue that this major release would not screw up much people's code as mentioned above, still, complete adoption of v4 won't happen within one day.

The changes listed as fixes both look good to me, changing the documentation can be done before release and sounds reasonable, as the introduction should probably be in normal English, and not all methods have descriptions and code examples. The second fix also seems reasonable, I don't think I need to further explain why.

The additional features all also seem to have good use-cases, the only thing I wonder about is if we should add more and more features to yargs, as it already has quite some features? But this rather is a question of yargs' philosophy, and I can't answer this one, I'm good with either decision and will try my best to contribute to making v4 happen.

**Comment by bcoe** [comment]
@maxrimue sorry I've been slow to give valuable feedback on this thread, this is awesome:

In the past, when we went from `v1` :arrow_right: `v2` :arrow_right: `v3`, we haven't made a huge effort to back-port features. I suggest we stick with this approach, we're not breaking the API so much that the upgrade path should be difficult for folks.

not to jinx us, but we rarely have bug reports float in at this point, and several of the enhancements that I'd like to see to yargs are breaking changes -- I propose the following:

1. let's create a `4.x` branch and start by tackling any of the changes listed in this ticket that are breaking.
2. each feature should still have its own branch, but we'll merge onto `4.x` rather than `master`.
3. once we've tackled a few of the breaking changes, we'll bite the bullet and bump yargs' major.

If you'd like to work on a ticket, just dibs it on this thread so that we don't step on each other's toes:

CC: @maxrimue, @nexdrew, @lrlna
